import streamlit as st
import pandas as pd
import numpy as np

from collections import defaultdict
import json
from urllib import parse
import os
import time 
import nltk 
nltk.download('punkt')
from nltk.tokenize import word_tokenize
from copy import deepcopy

import difflib 

import openai
openai.api_key = os.getenv("OPENAI_API_KEY")
# openai.api_key = st.secrets["OPENAI_API_KEY"]


def start_instruction():

    """
    Input: participant, role, writing task, writing content (prompt)
    -> Generate GPT-4 original text, and participants will revise the text
    -> Store them as a json (original, revision, change)
    """

    if 'gpt4_done' not in st.session_state:
        st.session_state.gpt4_done = False

    ### Instruction on the top page
    st.markdown("Thank you for participating in our research. Please read the instruction carefully, and follow them accordingly. Please contact at Minhwa Lee (lee03533@umn.edu) if you face any problem or seek help.")
    instruction_text = """ 
    <h2> Instruction </h2>
    <br>
    The objective of this study is to examine the writing behaviors and strategy for different groups of people on several topics. 
    Here are the detailed instructions:
    <ol>
        <li> Fill out the four blank forms in the section 'Generate Writing Template'.
        <li> After filling out all blanks, click 'Generate by GPT-4'. 
        <li> You will be given a passage that is generated by GPT-4 based on your input. Please revise the text as you would normally do. 
        <li> After finishing your revision, click the 'Submit Your Revision' button. 
    </ol>
    <br>
    <p> <span style="color:red"> WARNING : </span> Please follow each of steps in the instructions responsibly. Your response will be manually reviewed for the approval. <hr>          
    """
    st.markdown(instruction_text, unsafe_allow_html=True)
        
def main():
    st.set_page_config(page_title="Make Your Revision on GPT-4 Generated Writing Template!", 
                       page_icon="📝")
    
    start_instruction()

if __name__ == '__main__':
    main() 